[package]
name = "img_kernel_convolution"
version = "0.1.0"
authors = ["cyqsimon <28627918+cyqsimon@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
